version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: oracleorigin
      POSTGRES_PASSWORD: PSX001nva
      POSTGRES_DB: postgres